# Generated by Django 5.2.7 on 2025-10-25 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used_hours', models.FloatField(default=0.0)),
                ('cycle', models.CharField(default='70/8', max_length=10)),
                ('fuel_stop_every_miles', models.IntegerField(default=1000)),
                ('pickup_time_minutes', models.IntegerField(default=60)),
                ('dropoff_time_minutes', models.IntegerField(default=60)),
                ('route_distance_miles', models.FloatField(blank=True, null=True)),
                ('route_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('route_polyline', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ELDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('grid', models.JSONField(blank=True, null=True)),
                ('miles_today', models.FloatField(default=0.0)),
                ('driving_hours', models.FloatField(default=0.0)),
                ('on_duty_hours', models.FloatField(default=0.0)),
                ('sleeper_hours', models.FloatField(default=0.0)),
                ('off_duty_hours', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trips.trip')),
            ],
        ),
    ]
