# Generated by Django 5.2.7 on 2025-10-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='cycle',
            field=models.CharField(choices=[('70/8', '70 hours / 8 days'), ('60/7', '60 hours / 7 days')], default='70/8', max_length=10),
        ),
    ]
